name: Auto-merge PR

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-24.04
    if: |
      startsWith(github.head_ref, 'update-license-') ||
      github.head_ref == 'update-pre-commit-hooks' ||
      github.actor == 'dependabot[bot]'
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
