name: Close Stale Pull Requests

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale pull requests
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Staling issues and PR's
          days-before-stale: 7
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been open 7 days
            with no activity. Remove stale label or comment or this issue will be closed in 3 days
          stale-pr-message: |
            This PR has been automatically marked as stale because it has been open 7 days
            with no activity. Remove stale label or comment or this PR will be closed in 3 days
          # Not stale if have this labels or part of milestone
          exempt-issue-labels: bug,wip,on-hold,auto-update
          exempt-pr-labels:    bug,wip,on-hold
          exempt-all-milestones: true
          # Close issue operations
          # Label will be automatically removed if the issues are no longer closed nor locked.
          days-before-close: 3
          delete-branch: true
          close-issue-message: This issue was automatically closed because of stale in 3 days
          close-pr-message: This PR was automatically closed because of stale in 3 days
